let obj = {
  1: {
    strDrink: "Blue Bird",
    strInstructions: "",
    strDrinkThumb: "",
    strIngredient1: "blueberry schnapps",
    strIngredient2: "vodka",
    strIngredient3: "lime juice",
    strIngredient4: "ice",
    strIngredient5: "",
    strIngredient6: "",
    strIngredient7: "",
    strIngredient8: "",
    strIngredient9: "",
    strIngredient10: "",
    strIngredient11: "",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
  },
  2: {
    strDrink: "FaceMash",
    strInstructions: "",
    strDrinkThumb: "",
    strIngredient1: "bitters",
    strIngredient2: "spiced rum",
    strIngredient3: "absolut vodka",
    strIngredient4: "blue curacao",
    strIngredient5: "club soda",
    strIngredient6: "",
    strIngredient7: "",
    strIngredient8: "",
    strIngredient9: "",
    strIngredient10: "",
    strIngredient11: "",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
  },
  3: {
    strDrink: "InstaDrunk",
    strInstructions: "",
    strDrinkThumb: "",
    strIngredient1: "absinthe",
    strIngredient2: "gin",
    strIngredient3: "whiskey",
    strIngredient4: "scotch",
    strIngredient5: "tequila",
    strIngredient6: "",
    strIngredient7: "",
    strIngredient8: "",
    strIngredient9: "",
    strIngredient10: "",
    strIngredient11: "",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
  },
  4: {
    strDrink: "Strike",
    strInstructions: "",
    strDrinkThumb: "",
    strIngredient1: "apple schnapps",
    strIngredient2: "light rum",
    strIngredient3: "fresh lime juice",
    strIngredient4: "sour mix",
    strIngredient5: "",
    strIngredient6: "",
    strIngredient7: "",
    strIngredient8: "",
    strIngredient9: "",
    strIngredient10: "",
    strIngredient11: "",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
  },
  5: {
    strDrink: "",
    strInstructions: "",
    strDrinkThumb: "",
    strIngredient1: "",
    strIngredient2: "",
    strIngredient3: "",
    strIngredient4: "",
    strIngredient5: "",
    strIngredient6: "",
    strIngredient7: "",
    strIngredient8: "",
    strIngredient9: "",
    strIngredient10: "",
    strIngredient11: "",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
  }
}