let obj = {
  1: {
    strDrink: "Blue Bird",
    strInstructions: "",
    strDrinkThumb: "https://raw.githubusercontent.com/BenjaminT88/shake_it_up/master/frontend/public/images/BlueBird.png",
    strIngredient1: "blueberry schnapps",
    strIngredient2: "vodka",
    strIngredient3: "lime juice",
    strIngredient4: "ice",
    strMeasure1: "",
    strMeasure2: "",
    strMeasure3: "",
    strMeasure4: ""
  },
  2: {
    strDrink: "FaceMash",
    strInstructions: "",
    strDrinkThumb: "",
    strIngredient1: "bitters",
    strIngredient2: "spiced rum",
    strIngredient3: "absolut vodka",
    strIngredient4: "blue curacao",
    strIngredient5: "club soda",
    strMeasure1: "",
    strMeasure2: "",
    strMeasure3: "",
    strMeasure4: "",
    strMeasure5: ""
  },
  3: {
    strDrink: "InstaDrunk",
    strInstructions: "",
    strDrinkThumb: "https://raw.githubusercontent.com/BenjaminT88/shake_it_up/master/frontend/public/images/FaceMash.png",
    strIngredient1: "absinthe",
    strIngredient2: "gin",
    strIngredient3: "whiskey",
    strIngredient4: "scotch",
    strIngredient5: "tequila",
    strMeasure1: "",
    strMeasure2: "",
    strMeasure3: "",
    strMeasure4: "",
    strMeasure5: ""
  },
  4: {
    strDrink: "Strike",
    strInstructions: "",
    strDrinkThumb: "https://raw.githubusercontent.com/BenjaminT88/shake_it_up/master/frontend/public/images/Strike.png",
    strIngredient1: "apple schnapps",
    strIngredient2: "light rum",
    strIngredient3: "fresh lime juice",
    strIngredient4: "sour mix",
    strMeasure1: "",
    strMeasure2: "",
    strMeasure3: "",
    strMeasure4: ""
  },
  5: {
    strDrink: "DUUDE",
    strInstructions: "",
    strDrinkThumb: "https://raw.githubusercontent.com/BenjaminT88/shake_it_up/master/frontend/public/images/DUUDE.png",
    strIngredient1: "dark rum",
    strIngredient2: "dark creme de cacao",
    strIngredient3: "blackstrap rum",
    strIngredient4: "licorice root",
    strMeasure1: "",
    strMeasure2: "",
    strMeasure3: "",
    strMeasure4: ""
  },
  6: {
    strDrink: "Space Out",
    strInstructions: "",
    strDrinkThumb: "https://raw.githubusercontent.com/BenjaminT88/shake_it_up/master/frontend/public/images/SpaceOut.png",
    strIngredient1: "blackberry brandy",
    strIngredient2: "dark creme de cacao",
    strIngredient3: "espresso",
    strIngredient4: "nutmeg",
    strMeasure1: "",
    strMeasure2: "",
    strMeasure3: "",
    strMeasure4: ""
  },
  7: {
    strDrink: "Zimride",
    strInstructions: "",
    strDrinkThumb: "https://raw.githubusercontent.com/BenjaminT88/shake_it_up/master/frontend/public/images/Zimride.png",
    strIngredient1: "coconut rum",
    strIngredient2: "light cream",
    strIngredient3: "absolut vodka",
    strIngredient4: "sirup of roses",
    strMeasure1: "",
    strMeasure2: "",
    strMeasure3: "",
    strMeasure4: ""
  },
  8: {
    strDrink: "Airbed",
    strInstructions: "",
    strDrinkThumb: "https://raw.githubusercontent.com/BenjaminT88/shake_it_up/master/frontend/public/images/Airbed.png",
    strIngredient1: "passoa",
    strIngredient2: "red wine",
    strIngredient3: "maraschino cherry",
    strIngredient4: "kool-aid",
    strIngredient5: "ice",
    strMeasure1: "",
    strMeasure2: "",
    strMeasure3: "",
    strMeasure4: "",
    strMeasure5: ""
  },
  9: {
    strDrink: "Amazonked",
    strInstructions: "",
    strDrinkThumb: "https://raw.githubusercontent.com/BenjaminT88/shake_it_up/master/frontend/public/images/Amazonked.png",
    strIngredient1: "rye whiskey",
    strIngredient2: "southern comfort",
    strIngredient3: "root beer",
    strIngredient4: "cinnamon",
    strIngredient5: "orange spiral",
    strMeasure1: "",
    strMeasure2: "",
    strMeasure3: "",
    strMeasure4: "",
    strMeasure5: ""
  },
  10: {
    strDrink: "Liljohn",
    strInstructions: "",
    strDrinkThumb: "https://raw.githubusercontent.com/BenjaminT88/shake_it_up/master/frontend/public/images/Liljohn.png",
    strIngredient1: "absinthe",
    strIngredient2: "apple schnapps",
    strIngredient3: "blue curacao",
    strIngredient4: "green chartreuse",
    strIngredient5: "mint",
    strMeasure1: "",
    strMeasure2: "",
    strMeasure3: "",
    strMeasure4: "",
    strMeasure5: ""
  }
}